[build]
publish = "public"
command = "git submodule update -f --init && npm install && npm run build:functions && hugo"
image = "noble" # Ubuntu 24.04

# Configuration to keep logs private
[build.logSubdomainSuffix]
disable = true

[build.environment]
NODE_VERSION = "22"

[context.production.environment]
HUGO_VERSION = "v0.139.3"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[[headers]]
  for = "/users/hey"
  [headers.values]
    Content-Type = "application/activity+json"

[[headers]]
  for = "/outbox"
  [headers.values]
    Content-Type = "application/activity+json"

[[headers]]
  for = "/followers"
  [headers.values]
    Content-Type = "application/activity+json"

[[headers]]
  for = "/following"
  [headers.values]
    Content-Type = "application/activity+json"

[[headers]]
  for = "/.well-known/webfinger"
  [headers.values]
    Content-Type = "application/jrd+json"

[[redirects]]
from = "/lifestyle/*"
to = "/quote/lifestyle/:splat"
status = 301
force = true
query = { path = ":path" }

[[redirects]]
from = "/lifestyle/"
to = "/quote/lifestyle/"
status = 301
force = true
query = { path = ":path" }

# ActivityPub endpoints redirect functions
[[redirects]]
  from = "/.well-known/webfinger"
  to = "/.well-known/webfinger"
  status = 200
  force = true

[[redirects]]
  from = "/users/hey"
  to = "/users/hey"
  status = 200
  force = true

[[redirects]]
  from = "/inbox"
  to = "/.netlify/functions/inbox"
  status = 200
  force = true

[[redirects]]
  from = "/outbox"
  to = "/outbox"
  status = 200
  force = true

[[redirects]]
  from = "/followers"
  to = "/followers"
  status = 200
  force = true

[[redirects]]
  from = "/following"
  to = "/following"
  status = 200
  force = true

# Fallback route for intelligent redirection
[[redirects]]
  from = "/activitypub/*"
  to = "/.netlify/functions/activitypub"
  status = 200
  force = true

# Functions directory configuration
[functions]
  directory = "netlify/functions"
