name: Generate Outbox

on:
  push:
    paths:
      - "content/**"
      - ".github/workflows/generate-outbox.yml"
      - "scripts/generate_outbox.clj"
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Babashka
        uses: turtlequeue/setup-babashka@v1.7.0
        with:
          babashka-version: 1.3.189

      - name: Generate outbox
        run: |
          bb --config '{:deps {cheshire/cheshire {:mvn/version "5.12.0"}}}' .github/scripts/generate_outbox.clj

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add static/outbox static/content
          git commit -m "Update outbox for $(date +'%Y-%m')" || echo "No changes to commit"
          git push
