name: Generate Outbox

on:
  push:
    paths:
      - "content/blog/**"
      - ".github/workflows/generate-outbox.yml"
      - "scripts/generate_outbox.clj"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Babashka
        uses: turtlequeue/setup-babashka@v1.7.0
        with:
          babashka-version: 1.3.189

      - name: Install dependencies
        run: |
          bb --versiong
          bb --config '{:deps {cheshire/cheshire {:mvn/version "5.12.0"}}}' --eval "(require '[cheshire.core :as json])"

      - name: Generate outbox
        run: |
          bb --config '{:deps {cheshire/cheshire {:mvn/version "5.12.0"}}}' scripts/generate_outbox.clj

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add static/outbox
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update outbox" && git push)
