name: GitHub Contributions Timeline

on:
  schedule:
    # Executa no primeiro dia de cada mês às 00:00 UTC
    - cron: "0 */3 * * *"
  workflow_dispatch: # Permite execução manual

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  get-contributions:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Babashka
        uses: turtlequeue/setup-babashka@v1.7.0
        with:
          babashka-version: 1.12.208

      - name: Get current date
        id: date
        run: |
          echo "YEAR=$(date +'%Y')" >> $GITHUB_ENV
          echo "MONTH=$(date +'%m')" >> $GITHUB_ENV
          echo "Current date: $(date +'%Y-%m-%d')"

      - name: Get GitHub Contributions
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_USERNAME: avelino
        run: |
          # Calcular mês anterior
          CURRENT_MONTH=${{ env.MONTH }}
          CURRENT_YEAR=${{ env.YEAR }}

          if [ "$CURRENT_MONTH" = "01" ]; then
            PREV_MONTH=12
            PREV_YEAR=$((CURRENT_YEAR-1))
          else
            PREV_MONTH=$((CURRENT_MONTH-1))
            PREV_YEAR=$CURRENT_YEAR
          fi

          # Formatar o mês corretamente (adicionar zero à esquerda se necessário)
          PREV_MONTH=$(printf "%02d" $PREV_MONTH)

          echo "Generating report for: $PREV_YEAR-$PREV_MONTH"
          bb .github/scripts/github_contributions.clj $PREV_YEAR $PREV_MONTH

          echo "Generating report for: $CURRENT_YEAR-$CURRENT_MONTH"
          bb .github/scripts/github_contributions.clj $CURRENT_YEAR $CURRENT_MONTH

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add content/foss/*.md
          git commit -m "Update GitHub contributions for $(date +'%Y-%m')" || echo "No changes to commit"
          git push
